// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myserver;

namespace Myserver.Migrations
{
    [DbContext(typeof(ChatDBContext))]
    partial class ChatDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Myserver.Conversation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("f_userid")
                        .HasColumnType("int");

                    b.Property<int?>("s_userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("f_userid");

                    b.HasIndex("s_userid");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Myserver.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("conversationid")
                        .HasColumnType("int");

                    b.Property<string>("msg_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("msg_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("msg_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("msg_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("receiverid")
                        .HasColumnType("int");

                    b.Property<int?>("senderid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("conversationid");

                    b.HasIndex("receiverid");

                    b.HasIndex("senderid");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Myserver.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Myserver.Conversation", b =>
                {
                    b.HasOne("Myserver.User", "f_user")
                        .WithMany()
                        .HasForeignKey("f_userid");

                    b.HasOne("Myserver.User", "s_user")
                        .WithMany()
                        .HasForeignKey("s_userid");

                    b.Navigation("f_user");

                    b.Navigation("s_user");
                });

            modelBuilder.Entity("Myserver.Message", b =>
                {
                    b.HasOne("Myserver.Conversation", "conversation")
                        .WithMany("messages")
                        .HasForeignKey("conversationid");

                    b.HasOne("Myserver.User", "receiver")
                        .WithMany()
                        .HasForeignKey("receiverid");

                    b.HasOne("Myserver.User", "sender")
                        .WithMany()
                        .HasForeignKey("senderid");

                    b.Navigation("conversation");

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("Myserver.Conversation", b =>
                {
                    b.Navigation("messages");
                });
#pragma warning restore 612, 618
        }
    }
}
